Repository callback-demons/callback-news-api, pull requests merged in 2020-05, with the labels that each got.

#33 added initial config
  .gitignore
  app/.env.dev
  app/Dockerfile
  app/api_news/__init__.py
  app/api_news/asgi.py
  app/api_news/settings.py
  app/api_news/urls.py
  app/api_news/wsgi.py
  app/entrypoint.sh
  app/env/bin/activate
  app/env/bin/activate.csh
  app/env/bin/activate.fish
  app/env/bin/django-admin
  app/env/bin/django-admin.py
  app/env/bin/easy_install
  app/env/bin/easy_install-3.7
  app/env/bin/pip
  app/env/bin/pip3
  app/env/bin/pip3.7
  app/env/bin/python
  app/env/bin/python3
  app/env/bin/sqlformat
  app/env/pyvenv.cfg
  app/manage.py
  app/requirements.txt
  docker-compose.yml
  docker/nginx.conf
Labels: setting

#35 Fixing django and nginx conf files to correct deployment of doker container.
  .gitignore
  LICENSE
  app/.env.dev
  app/Dockerfile
  app/api_news/asgi.py
  app/api_news/settings.py
  app/api_news/urls.py
  app/api_news/wsgi.py
  app/env/bin/activate
  app/env/bin/activate.csh
  app/env/bin/activate.fish
  app/env/bin/django-admin
  app/env/bin/django-admin.py
  app/env/bin/easy_install
  app/env/bin/easy_install-3.7
  app/env/bin/pip
  app/env/bin/pip3
  app/env/bin/pip3.7
  app/env/bin/sqlformat
  app/env/pyvenv.cfg
  app/manage.py
  app/requirements.txt
  docker-compose.yml
  docker/nginx.conf
Labels: setting

#40 Account managment
  django-on-docker/app/api/urls.py
  django-on-docker/app/users/migrations/0004_auto_20200528_1223.py
  django-on-docker/app/users/models.py
  django-on-docker/app/users/serializers.py
  django-on-docker/app/users/urls.py
  django-on-docker/app/users/views.py
Labels: feature

#41 [FEATURE]`comments`:added actions for comments in news
  django-on-docker/app/api/urls.py
  django-on-docker/app/categories/urls.py
  django-on-docker/app/comments/views.py
Labels: feature

#46 [FEATURE]`Storage setting`:add support cloud storages
  .env.dev
  README.md
  app/.env.dev
  app/Dockerfile
  app/api/settings/__init__.py
  app/api/settings/dev.py
  app/api/settings/prod.py
  app/requirements/base.txt
  app/requirements/dev.txt
  app/requirements/prod.txt
  docker-compose.yml
Labels: feature

#47 Feature/storage
  .env.dev
  README.md
  app/api/settings/dev.py
  app/api/settings/prod.py
Labels: documentation, feature

#51 [FEATURE]`news pagnation`:added pagination to news
  app/news/serializers.py
  app/news/views.py
Labels: feature

#50 Feature/news collector integraton
  app/api/urls.py
  app/categories/migrations/0006_auto_20200530_1353.py
  app/media/migrations/0007_auto_20200530_1353.py
  app/media/migrations/0008_auto_20200530_1446.py
  app/media/models.py
  app/news/migrations/0010_auto_20200530_1353.py
  app/sources/admin.py
  app/sources/migrations/0005_auto_20200530_1351.py
  app/sources/migrations/0006_auto_20200530_1403.py
  app/sources/models.py
  app/sources/serializers.py
  app/sources/urls.py
  app/sources/views.py
  app/users/migrations/0005_auto_20200530_1353.py
Labels: feature

#54 configuration jenkins file to deploy
  Jenkinsfile
Labels: infrastructure

#55 [Feature]`like button`:<logic for like on news>
  app/news/migrations/0011_auto_20200530_1851.py
  app/news/models.py
  app/news/urls.py
  app/news/views.py
Labels: feature

#58 Hotfix/changes auth
  app/comments/urls.py
  app/users/migrations/0007_auto_20200531_0043.py
  app/users/models.py
  app/users/serializers.py
  app/users/views.py
Labels: bug

#61 Return the id with token
  app/api/urls.py
  app/news/views.py
  app/users/views.py
Labels: feature

#62 delete git reset
  Jenkinsfile
Labels: infrastructure

#63 added user to comments
  app/comments/serializers.py
  app/comments/views.py
Labels: feature

#64 Feature/news data
  app/news/migrations/0012_auto_20200531_1216.py
  app/news/migrations/0013_remove_news_likes.py
  app/news/migrations/0014_auto_20200531_1612.py
  app/news/migrations/0015_auto_20200531_1614.py
  app/news/models.py
  app/news/serializers.py
  app/news/urls.py
  app/news/views.py
Labels: feature

#65 [FIX] restore username in users model and return all the fields of model
  app/api/settings/dev.py
  app/news/migrations/0012_auto_20200531_1632.py
  app/news/models.py
  app/users/migrations/0008_auto_20200531_1703.py
  app/users/migrations/0009_auto_20200531_1709.py
  app/users/migrations/0010_auto_20200531_1709.py
  app/users/migrations/0011_auto_20200531_1715.py
  app/users/migrations/0012_remove_user_nickname.py
  app/users/models.py
  app/users/serializers.py
Labels: bug

#66 Comments by user, news sorted and username restore
  Jenkinsfile
  app/api/settings/dev.py
  app/comments/serializers.py
  app/comments/views.py
  app/news/migrations/0012_auto_20200531_1216.py
  app/news/migrations/0012_auto_20200531_1632.py
  app/news/migrations/0013_remove_news_likes.py
  app/news/migrations/0014_auto_20200531_1612.py
  app/news/migrations/0015_auto_20200531_1614.py
  app/news/models.py
  app/news/serializers.py
  app/news/urls.py
  app/news/views.py
  app/users/migrations/0008_auto_20200531_1703.py
  app/users/migrations/0009_auto_20200531_1709.py
  app/users/migrations/0010_auto_20200531_1709.py
  app/users/migrations/0011_auto_20200531_1715.py
  app/users/migrations/0012_remove_user_nickname.py
  app/users/models.py
  app/users/serializers.py
Labels: feature
